### GET links for user with id
GET http://localhost:8000/api/admin/users/6/links

### CREATE links with product id
POST http://localhost:8000/api/ambassador/links
Content-Type: application/json

{
  "products": [2, 5]
}

### GET links with code
http://localhost:8000/api/checkout/links/rl52cwe